# Usar una imagen base de Java
FROM openjdk:17-jdk-alpine

# Establecer el directorio de trabajo en el contenedor
WORKDIR /app

# Copiar el archivo JAR de la aplicación en el contenedor
COPY target/proyectoFinal-0.0.1-SNAPSHOT.jar app.jar

# Exponer el puerto en el que correrá la aplicación
EXPOSE 9010

# Comando para ejecutar la aplicación
ENTRYPOINT ["java", "-jar", "app.jar"]
